### ISSUE TITLE
Running SourceInitFile

### ISSUE THREAD

**Issue by gardenof** [flipstone/vimstone#2]
Get  ot the last step "then run :SourceInitFile"

<img width="713" alt="Screen Shot 2019-05-07 at 4 32 05 PM" src="https://user-images.githubusercontent.com/1392255/57331046-b6e82680-70e5-11e9-949c-16ed740a6eb4.png">

**Comment by qxjit** [comment]
This was fixed by 62ad2c0a3347d4eb9d922c7de78b39ed491c63bf, but I fat fingered the PR number in the commit message :cry:
